// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Content Enricher (EIP)
// https://www.enterpriseintegrationpatterns.com/patterns/messaging/DataEnricher.html
//
// Augments the canonical message with reference data the alert-engine needs:
// vehicle display name, metric thresholds (warn/critical), calibration offset,
// and a rolling average of recent readings. The enriched message is self-contained
// so downstream components need no further lookups.

export class ContentEnricher {
  constructor(vehicleRegistry = {}, thresholdRegistry = {}, rollingWindow = 5) {
    this.vehicleRegistry = vehicleRegistry;
    this.thresholdRegistry = thresholdRegistry;
    this.rollingWindow = rollingWindow;
    this.history = new Map();
  }

  enrich(message) {
    const { vehicleId, metric, value } = message;

    const vehicle = this.vehicleRegistry[vehicleId] ?? { name: vehicleId };
    const thresholds = this.thresholdRegistry[metric] ?? {
      warnThreshold: Infinity,
      critThreshold: Infinity,
      calibrationOffset: 0,
    };

    const calibratedValue = value + thresholds.calibrationOffset;

    const key = `${vehicleId}:${metric}`;
    if (!this.history.has(key)) this.history.set(key, []);
    const buf = this.history.get(key);
    buf.push(calibratedValue);
    if (buf.length > this.rollingWindow) buf.shift();
    const rollingAvg = buf.reduce((a, b) => a + b, 0) / buf.length;

    return {
      ...message,
      value: calibratedValue,
      vehicleName: vehicle.name,
      warnThreshold: thresholds.warnThreshold,
      critThreshold: thresholds.critThreshold,
      rollingAvg: parseFloat(rollingAvg.toFixed(3)),
    };
  }
}
