// Generated by Claude Code — CS 3660 Sprint 2
// Gateway: subscribe to raw readings, run the EIP pipeline, publish clean messages.
// Pipeline: MessageTranslator -> MessageRouter -> ContentEnricher
// This is also the Pipes-and-Filters structure from Sprint 1, reused here.

import { createBusClient } from '../bus/mqttBus.js';
import { MessageTranslator } from './MessageTranslator.js';
import { MessageRouter } from './MessageRouter.js';
import { ContentEnricher } from './ContentEnricher.js';

// Vehicle and threshold reference data (extend as needed)
const VEHICLE_REGISTRY = {
  'vehicle-1': { name: 'Truck Alpha' },
  'vehicle-2': { name: 'Truck Bravo' },
  'vehicle-3': { name: 'Truck Charlie' },
};

const THRESHOLD_REGISTRY = {
  coolantTemp: { warnThreshold: 100, critThreshold: 110, calibrationOffset: 0 },
  oilPressure: { warnThreshold: 25,  critThreshold: 15,  calibrationOffset: 0 },
  rpm:         { warnThreshold: 3500, critThreshold: 4000, calibrationOffset: 0 },
  fuelLevel:   { warnThreshold: 20,  critThreshold: 10,  calibrationOffset: 0 },
};

const ROUTE_MAP = {
  '*': 'fleet/{vehicleId}/{metric}/clean',
};

const translator = new MessageTranslator();
const router = new MessageRouter(ROUTE_MAP);
const enricher = new ContentEnricher(VEHICLE_REGISTRY, THRESHOLD_REGISTRY);

async function main() {
  const client = await createBusClient(`gateway-${Date.now()}`, { clean: true });

  client.subscribe('fleet/+/raw', { qos: 1 }, (err) => {
    if (err) {
      console.error('[gateway] subscribe error:', err.message);
      process.exit(1);
    }
    console.log('[gateway] subscribed to fleet/+/raw');
  });

  client.on('message', (topic, buffer) => {
    let raw;
    try {
      raw = JSON.parse(buffer.toString());
    } catch (err) {
      console.warn('[gateway] could not parse message on', topic, err.message);
      return;
    }

    try {
      // Step 1: Translate to canonical schema
      const canonical = translator.translate(raw);

      // Step 2: Route to the correct output topic
      const outTopic = router.route(canonical);

      // Step 3: Enrich with reference data
      const enriched = enricher.enrich(canonical);

      client.publish(outTopic, JSON.stringify(enriched), { qos: 1, retain: true }, (err) => {
        if (err) console.error('[gateway] publish error:', err.message);
      });
    } catch (err) {
      console.error('[gateway] pipeline error:', err.message, 'raw:', raw);
    }
  });
}

main().catch((err) => {
  console.error('[gateway] fatal:', err);
  process.exit(1);
});
