// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Message Translator (EIP)
// https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageTranslator.html
//
// Converts the raw device payload into a canonical internal schema with
// consistent field names, normalized units, and ISO-8601 timestamps.
// Every downstream component can rely on this schema without caring about
// device-specific payload formats.

export class MessageTranslator {
  /**
   * Translate a raw device payload into the canonical internal format.
   *
   * Raw shape: { vehicleId, metric, value, unit, ts }
   * Canonical shape: {
   *   vehicleId: string,
   *   metric:    string,
   *   value:     number,
   *   unit:      string,
   *   ts:        string,  // ISO-8601
   *   receivedAt: string, // ISO-8601 — when the gateway ingested it
   *   raw:       object,  // original payload preserved for audit
   * }
   *
   * @param {object} rawPayload - Parsed JSON from the MQTT message.
   * @returns {object} Canonical message.
   * @throws {Error} If required fields are missing or value is not numeric.
   */
  translate(rawPayload) {
    const { vehicleId, metric, value, unit, ts } = rawPayload;

    if (!vehicleId || typeof vehicleId !== 'string') {
      throw new Error(`MessageTranslator: missing or invalid vehicleId`);
    }
    if (!metric || typeof metric !== 'string') {
      throw new Error(`MessageTranslator: missing or invalid metric`);
    }
    if (typeof value !== 'number' || !isFinite(value)) {
      throw new Error(`MessageTranslator: value must be a finite number, got ${value}`);
    }

    return {
      vehicleId,
      metric,
      value,
      unit: unit ?? 'unknown',
      ts: ts ?? new Date().toISOString(),
      receivedAt: new Date().toISOString(),
      raw: rawPayload,
    };
  }
}
