// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Message Router / Content-Based Router (EIP)
// https://www.enterpriseintegrationpatterns.com/patterns/messaging/ContentBasedRouter.html

export class MessageRouter {
  constructor(routeMap = {}) {
    this.routeMap = routeMap;
  }

  route(message) {
    const { vehicleId, metric } = message;
    const template = this.routeMap[metric] ?? this.routeMap['*'];
    if (!template) {
      throw new Error(`MessageRouter: no route defined for metric "${metric}"`);
    }
    return template
      .replace('{vehicleId}', vehicleId)
      .replace('{metric}', metric);
  }
}
