// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Message Router / Content-Based Router (EIP)
// https://www.enterpriseintegrationpatterns.com/patterns/messaging/ContentBasedRouter.html
//
// Inspects the canonical message's metric field and routes it to the correct
// downstream topic. Different metrics require different handling downstream,
// so routing ensures each message reaches the right consumer.

export class MessageRouter {
  /**
   * @param {object} routeMap - Map of metric name to output topic template.
   *   Template may use {vehicleId} and {metric} placeholders.
   *   Example: { coolantTemp: 'fleet/{vehicleId}/coolantTemp/clean', '*': 'fleet/{vehicleId}/{metric}/clean' }
   */
  constructor(routeMap = {}) {
    this.routeMap = routeMap;
  }

  /**
   * Resolve the output topic for a canonical message.
   *
   * @param {object} message - Canonical message from MessageTranslator.
   * @returns {string} The MQTT topic to publish the enriched message on.
   * @throws {Error} If no route matches and no wildcard '*' is defined.
   */
  route(message) {
    const { vehicleId, metric } = message;

    const template = this.routeMap[metric] ?? this.routeMap['*'];
    if (!template) {
      throw new Error(`MessageRouter: no route defined for metric "${metric}"`);
    }

    return template
      .replace('{vehicleId}', vehicleId)
      .replace('{metric}', metric);
  }
}
