// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Message Translator (EIP)
// https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageTranslator.html

export class MessageTranslator {
  translate(rawPayload) {
    const { vehicleId, metric, value, unit, ts } = rawPayload;

    if (!vehicleId || typeof vehicleId !== 'string') {
      throw new Error('MessageTranslator: missing or invalid vehicleId');
    }
    if (!metric || typeof metric !== 'string') {
      throw new Error('MessageTranslator: missing or invalid metric');
    }
    if (typeof value !== 'number' || !isFinite(value)) {
      throw new Error(`MessageTranslator: value must be a finite number, got ${value}`);
    }

    return {
      vehicleId,
      metric,
      value,
      unit: unit ?? 'unknown',
      ts: ts ?? new Date().toISOString(),
      receivedAt: new Date().toISOString(),
      raw: rawPayload,
    };
  }
}
