// Generated by Claude Code — CS 3660 Sprint 2
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { ContentEnricher } from '../src/gateway/ContentEnricher.js';

const vehicles = { 'v1': { name: 'Truck Alpha' } };
const thresholds = {
  coolantTemp: { warnThreshold: 100, critThreshold: 110, calibrationOffset: 2 },
};

const enricher = new ContentEnricher(vehicles, thresholds);

const baseMsg = { vehicleId: 'v1', metric: 'coolantTemp', value: 95, unit: 'C', ts: '2026-06-01T00:00:00.000Z', receivedAt: '2026-06-01T00:00:00.000Z', raw: {} };

test('enrich: adds vehicleName', () => {
  const result = enricher.enrich(baseMsg);
  assert.equal(result.vehicleName, 'Truck Alpha');
});

test('enrich: applies calibrationOffset to value', () => {
  const result = enricher.enrich({ ...baseMsg, value: 95 });
  assert.equal(result.value, 97); // 95 + 2
});

test('enrich: adds warnThreshold and critThreshold', () => {
  const result = enricher.enrich(baseMsg);
  assert.equal(result.warnThreshold, 100);
  assert.equal(result.critThreshold, 110);
});

test('enrich: adds rollingAvg', () => {
  const result = enricher.enrich(baseMsg);
  assert.ok(typeof result.rollingAvg === 'number');
});

test('enrich: defaults vehicleName to vehicleId for unknown vehicle', () => {
  const result = enricher.enrich({ ...baseMsg, vehicleId: 'unknown-99' });
  assert.equal(result.vehicleName, 'unknown-99');
});
