// Generated by Claude Code — CS 3660 Sprint 2
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { isWarning, isCritical, isBackToNormal, sustained, isStale } from '../src/alert-engine/alertMachine.js';

test('isWarning: true when value between warn and crit', () => {
  assert.equal(isWarning(102, 100, 110), true);
});

test('isWarning: false when value below warn', () => {
  assert.equal(isWarning(90, 100, 110), false);
});

test('isWarning: false when value at or above crit', () => {
  assert.equal(isWarning(110, 100, 110), false);
});

test('isCritical: true at threshold', () => {
  assert.equal(isCritical(110, 110), true);
});

test('isCritical: true above threshold', () => {
  assert.equal(isCritical(115, 110), true);
});

test('isCritical: false below threshold', () => {
  assert.equal(isCritical(109, 110), false);
});

test('isBackToNormal: true when below (warn - margin)', () => {
  assert.equal(isBackToNormal(94, 100, 5), true);
});

test('isBackToNormal: false when above (warn - margin)', () => {
  assert.equal(isBackToNormal(96, 100, 5), false);
});

test('sustained: true when count meets required', () => {
  assert.equal(sustained(3, 3), true);
});

test('sustained: false when count is below required', () => {
  assert.equal(sustained(2, 3), false);
});

test('isStale: true when lastSeen is old', () => {
  const old = new Date(Date.now() - 60000).toISOString();
  assert.equal(isStale(old, 30000), true);
});

test('isStale: false when lastSeen is recent', () => {
  const recent = new Date(Date.now() - 5000).toISOString();
  assert.equal(isStale(recent, 30000), false);
});

test('isStale: true when lastSeen is null', () => {
  assert.equal(isStale(null, 30000), true);
});

// lowIsBad=true tests (oilPressure / fuelLevel direction)
test('isCritical (lowIsBad): true when value at or below critThreshold', () => {
  assert.equal(isCritical(15, 15, true), true);
});

test('isCritical (lowIsBad): true when value below critThreshold', () => {
  assert.equal(isCritical(10, 15, true), true);
});

test('isCritical (lowIsBad): false when value above critThreshold', () => {
  assert.equal(isCritical(45, 15, true), false);
});

test('isWarning (lowIsBad): true when value between crit and warn', () => {
  assert.equal(isWarning(20, 25, 15, true), true);
});

test('isWarning (lowIsBad): false when value above warnThreshold (normal)', () => {
  assert.equal(isWarning(45, 25, 15, true), false);
});

test('isBackToNormal (lowIsBad): true when value exceeds warn + margin', () => {
  assert.equal(isBackToNormal(30, 25, 3, true), true);
});

test('isBackToNormal (lowIsBad): false when value is still in warning zone', () => {
  assert.equal(isBackToNormal(26, 25, 3, true), false);
});
