// Generated by Claude Code — CS 3660 Sprint 2
// Integration test: end-to-end pipeline, in-process, no MQTT required.
//
// Simulates a device reading flowing through the full stack:
//   MessageTranslator -> MessageRouter -> ContentEnricher
//   -> XState alert machine -> EventDispatcher -> AuditLogger -> eventStore
//
// Verifies:
//   1. Gateway EIP pipeline produces a correctly enriched clean message.
//   2. Alert machine transitions to the expected state on the enriched reading.
//   3. Observer fan-out: AuditLogger AND WsBridgeObserver both fire.
//   4. AuditLogger writes events to the SQLite event store.
//   5. Event store supports point-in-time replay via upToTime.
//   6. Hash chain is intact after appending events.

// Set SQLITE_PATH before any project module loads so the singleton db
// picks up the test path. Static imports above (node:*) are Node builtins
// and do not load config.js, so this assignment runs before config.js is
// evaluated by the dynamic imports below.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { rmSync, existsSync } from 'node:fs';
import os from 'node:os';
import { join } from 'node:path';
import { createActor } from 'xstate';

const TEST_DB = join(os.tmpdir(), `fleet-integration-${Date.now()}.db`);
process.env.SQLITE_PATH = TEST_DB;

// Dynamic imports after env var is set so config.js reads the test path.
const { MessageTranslator }  = await import('../src/gateway/MessageTranslator.js');
const { MessageRouter }      = await import('../src/gateway/MessageRouter.js');
const { ContentEnricher }    = await import('../src/gateway/ContentEnricher.js');
const { createAlertMachine } = await import('../src/alert-engine/alertMachine.js');
const { EventDispatcher }    = await import('../src/events/EventDispatcher.js');
const { AuditLogger }        = await import('../src/events/AuditLogger.js');
const { WsBridgeObserver }   = await import('../src/events/WsBridgeObserver.js');
const { appendEvent, getEvents, verifyChain } = await import('../src/events/eventStore.js');

// ---- Shared fixtures ----

const RAW_CRITICAL = {
  vehicleId: 'int-vehicle-1',
  metric: 'coolantTemp',
  value: 115,       // >= critThreshold 110
  unit: 'celsius',
  ts: new Date().toISOString(),
};

const ROUTE_MAP = { '*': 'fleet/{vehicleId}/{metric}/clean' };

const THRESHOLD_REGISTRY = {
  coolantTemp: { warnThreshold: 100, critThreshold: 110, calibrationOffset: 0 },
};

const CHANNEL_CONFIG = {
  warnThreshold: 100,
  critThreshold: 110,
  hysteresisMargin: 5,
  sustainedReadings: 1,
  stalenessMs: 30000,
  lowIsBad: false,
};

// ---- 1. EIP Gateway pipeline ----

test('MessageTranslator produces canonical shape with receivedAt and raw', () => {
  const translator = new MessageTranslator();
  const canonical = translator.translate(RAW_CRITICAL);
  assert.equal(canonical.vehicleId, 'int-vehicle-1');
  assert.equal(canonical.metric, 'coolantTemp');
  assert.equal(canonical.value, 115);
  assert.ok(canonical.receivedAt, 'receivedAt should be present');
  assert.deepEqual(canonical.raw, RAW_CRITICAL);
});

test('MessageRouter resolves correct clean topic', () => {
  const translator = new MessageTranslator();
  const router = new MessageRouter(ROUTE_MAP);
  const topic = router.route(translator.translate(RAW_CRITICAL));
  assert.equal(topic, 'fleet/int-vehicle-1/coolantTemp/clean');
});

test('ContentEnricher augments canonical message with threshold fields and rollingAvg', () => {
  const translator = new MessageTranslator();
  const enricher = new ContentEnricher({}, THRESHOLD_REGISTRY);
  const enriched = enricher.enrich(translator.translate(RAW_CRITICAL));
  assert.equal(enriched.warnThreshold, 100);
  assert.equal(enriched.critThreshold, 110);
  assert.ok('rollingAvg' in enriched, 'rollingAvg should be present');
});

test('full EIP pipeline: raw -> canonical -> routed -> enriched', () => {
  const translator = new MessageTranslator();
  const router = new MessageRouter(ROUTE_MAP);
  const enricher = new ContentEnricher({}, THRESHOLD_REGISTRY);

  const canonical = translator.translate(RAW_CRITICAL);
  const topic = router.route(canonical);
  const enriched = enricher.enrich(canonical);

  assert.equal(topic, 'fleet/int-vehicle-1/coolantTemp/clean');
  assert.equal(enriched.vehicleId, 'int-vehicle-1');
  assert.equal(enriched.value, 115); // calibrationOffset = 0
  assert.equal(enriched.warnThreshold, 100);
});

// ---- 2. Alert machine processes enriched reading ----

test('alert machine transitions to CRITICAL given enriched critical reading', () => {
  const translator = new MessageTranslator();
  const enricher = new ContentEnricher({}, THRESHOLD_REGISTRY);
  const enriched = enricher.enrich(translator.translate(RAW_CRITICAL));

  const actor = createActor(createAlertMachine(CHANNEL_CONFIG));
  actor.start();
  actor.send({ type: 'READING', value: enriched.value, ts: enriched.ts });

  assert.equal(actor.getSnapshot().value, 'CRITICAL');
});

// ---- 3. Observer fan-out ----

test('EventDispatcher delivers to multiple subscribers (fan-out)', () => {
  const dispatcher = new EventDispatcher();
  const calls = [];
  dispatcher.subscribe('ReadingRecorded', (type, payload) => calls.push({ source: 'A', type }));
  dispatcher.subscribe('ReadingRecorded', (type, payload) => calls.push({ source: 'B', type }));

  dispatcher.dispatch('ReadingRecorded', {
    vehicleId: 'v-fanout',
    metric: 'rpm',
    aggregateId: 'v-fanout:rpm',
    value: 3600,
    ts: new Date().toISOString(),
  });

  assert.equal(calls.length, 2);
  assert.equal(calls[0].source, 'A');
  assert.equal(calls[1].source, 'B');
});

test('WsBridgeObserver fires and serializes payload on AlertStateChanged', () => {
  const dispatcher = new EventDispatcher();
  const received = [];
  new WsBridgeObserver(dispatcher, (msg) => received.push(JSON.parse(msg)));

  dispatcher.dispatch('AlertStateChanged', {
    vehicleId: 'v-ws',
    metric: 'coolantTemp',
    aggregateId: 'v-ws:coolantTemp',
    state: 'WARNING',
    ts: new Date().toISOString(),
  });

  assert.equal(received.length, 1);
  assert.equal(received[0].eventType, 'AlertStateChanged');
  assert.equal(received[0].payload.state, 'WARNING');
});

test('AuditLogger and WsBridgeObserver both fire from the same dispatch', () => {
  const dispatcher = new EventDispatcher();
  const wsReceived = [];

  new AuditLogger(dispatcher);
  new WsBridgeObserver(dispatcher, (msg) => wsReceived.push(JSON.parse(msg)));

  const aggregateId = 'fanout-dual:coolantTemp';
  dispatcher.dispatch('AlertStateChanged', {
    vehicleId: 'fanout-dual',
    metric: 'coolantTemp',
    aggregateId,
    state: 'CRITICAL',
    ts: new Date().toISOString(),
  });

  // WsBridgeObserver fired
  assert.equal(wsReceived.length, 1);
  assert.equal(wsReceived[0].payload.state, 'CRITICAL');

  // AuditLogger wrote to store
  const stored = getEvents('channel', aggregateId);
  assert.ok(stored.length >= 1, 'AuditLogger should have written to the event store');
  assert.equal(stored[stored.length - 1].event_type, 'AlertStateChanged');
});

// ---- 4. Event store writes ----

test('AuditLogger appends ReadingRecorded to the event store', () => {
  const dispatcher = new EventDispatcher();
  new AuditLogger(dispatcher);

  const aggregateId = 'store-test-1:coolantTemp';
  dispatcher.dispatch('ReadingRecorded', {
    vehicleId: 'store-test-1',
    metric: 'coolantTemp',
    aggregateId,
    value: 115,
    ts: new Date().toISOString(),
  });

  const events = getEvents('channel', aggregateId);
  assert.ok(events.length >= 1);
  assert.equal(events[events.length - 1].event_type, 'ReadingRecorded');
  assert.equal(events[events.length - 1].aggregate_id, aggregateId);
});

test('event store payload round-trips through JSON correctly', () => {
  const dispatcher = new EventDispatcher();
  new AuditLogger(dispatcher);

  const aggregateId = 'store-test-2:rpm';
  const ts = new Date().toISOString();

  dispatcher.dispatch('ReadingRecorded', {
    vehicleId: 'store-test-2',
    metric: 'rpm',
    aggregateId,
    value: 3800,
    ts,
  });

  const events = getEvents('channel', aggregateId);
  const payload = JSON.parse(events[events.length - 1].payload);
  assert.equal(payload.value, 3800);
  assert.equal(payload.metric, 'rpm');
});

// ---- 5. Full end-to-end pipeline ----

test('full pipeline: raw reading produces ReadingRecorded and AlertStateChanged in store', () => {
  const dispatcher = new EventDispatcher();
  new AuditLogger(dispatcher);

  const translator = new MessageTranslator();
  const enricher = new ContentEnricher({}, THRESHOLD_REGISTRY);

  const raw = {
    vehicleId: 'e2e-v1',
    metric: 'coolantTemp',
    value: 105,       // warning range
    unit: 'celsius',
    ts: new Date().toISOString(),
  };

  const enriched = enricher.enrich(translator.translate(raw));
  const actor = createActor(createAlertMachine(CHANNEL_CONFIG));
  actor.start();
  actor.send({ type: 'READING', value: enriched.value, ts: enriched.ts });

  const state = actor.getSnapshot().value;
  assert.equal(state, 'WARNING');

  const aggregateId = `${enriched.vehicleId}:${enriched.metric}`;

  dispatcher.dispatch('ReadingRecorded', {
    vehicleId: enriched.vehicleId,
    metric: enriched.metric,
    aggregateId,
    value: enriched.value,
    ts: enriched.ts,
  });
  dispatcher.dispatch('AlertStateChanged', {
    vehicleId: enriched.vehicleId,
    metric: enriched.metric,
    aggregateId,
    state,
    ts: enriched.ts,
  });

  const events = getEvents('channel', aggregateId);
  assert.equal(events.length, 2);
  assert.equal(events[0].event_type, 'ReadingRecorded');
  assert.equal(events[1].event_type, 'AlertStateChanged');
  assert.equal(JSON.parse(events[1].payload).state, 'WARNING');
});

// ---- 6. Hash chain integrity ----

test('event store hash chain is intact after multiple appends', () => {
  const aggregateId = 'hash-test:coolantTemp';

  appendEvent({
    aggregateType: 'channel',
    aggregateId,
    eventType: 'ReadingRecorded',
    payload: { vehicleId: 'hash-test', metric: 'coolantTemp', value: 105 },
    occurredAt: new Date().toISOString(),
  });
  appendEvent({
    aggregateType: 'channel',
    aggregateId,
    eventType: 'AlertStateChanged',
    payload: { vehicleId: 'hash-test', metric: 'coolantTemp', state: 'WARNING' },
    occurredAt: new Date().toISOString(),
  });

  assert.equal(verifyChain('channel', aggregateId), true);
});

// ---- 7. Point-in-time replay ----

test('getEvents with upToTime returns only events at or before the cutoff', () => {
  const aggregateId = 'timetravel:fuelLevel';

  const past   = new Date(Date.now() - 10000).toISOString();
  const recent = new Date().toISOString();

  appendEvent({
    aggregateType: 'channel',
    aggregateId,
    eventType: 'ReadingRecorded',
    payload: { value: 50, note: 'past event' },
    occurredAt: past,
  });
  appendEvent({
    aggregateType: 'channel',
    aggregateId,
    eventType: 'AlertStateChanged',
    payload: { state: 'WARNING', note: 'recent event' },
    occurredAt: recent,
  });

  const historical = getEvents('channel', aggregateId, { upToTime: past });
  assert.equal(historical.length, 1);
  assert.equal(historical[0].event_type, 'ReadingRecorded');
  assert.equal(JSON.parse(historical[0].payload).note, 'past event');
});

// Clean up the test database when the process exits.
process.on('exit', () => {
  try { if (existsSync(TEST_DB)) rmSync(TEST_DB); } catch { /* best-effort */ }
});
