// Generated by Claude Code — CS 3660 Sprint 2
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { MessageTranslator } from '../src/gateway/MessageTranslator.js';

const translator = new MessageTranslator();

test('translate: produces canonical fields from valid raw payload', () => {
  const raw = { vehicleId: 'v1', metric: 'coolantTemp', value: 95.5, unit: 'C', ts: '2026-06-01T00:00:00.000Z' };
  const result = translator.translate(raw);
  assert.equal(result.vehicleId, 'v1');
  assert.equal(result.metric, 'coolantTemp');
  assert.equal(result.value, 95.5);
  assert.equal(result.unit, 'C');
  assert.equal(result.ts, '2026-06-01T00:00:00.000Z');
  assert.ok(result.receivedAt);
  assert.deepEqual(result.raw, raw);
});

test('translate: throws when vehicleId is missing', () => {
  assert.throws(() => translator.translate({ metric: 'coolantTemp', value: 95 }), /vehicleId/);
});

test('translate: throws when value is not a number', () => {
  assert.throws(() => translator.translate({ vehicleId: 'v1', metric: 'rpm', value: 'fast' }), /value/);
});

test('translate: defaults unit to unknown when missing', () => {
  const result = translator.translate({ vehicleId: 'v1', metric: 'rpm', value: 2200 });
  assert.equal(result.unit, 'unknown');
});
