// Generated by Claude Code — CS 3660 Sprint 2
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { MessageRouter } from '../src/gateway/MessageRouter.js';

const router = new MessageRouter({
  coolantTemp: 'fleet/{vehicleId}/coolantTemp/clean',
  '*': 'fleet/{vehicleId}/{metric}/clean',
});

test('route: resolves exact metric match', () => {
  const topic = router.route({ vehicleId: 'v1', metric: 'coolantTemp' });
  assert.equal(topic, 'fleet/v1/coolantTemp/clean');
});

test('route: falls back to wildcard for unknown metric', () => {
  const topic = router.route({ vehicleId: 'v2', metric: 'rpm' });
  assert.equal(topic, 'fleet/v2/rpm/clean');
});

test('route: throws when no route and no wildcard', () => {
  const strictRouter = new MessageRouter({ coolantTemp: 'fleet/{vehicleId}/coolantTemp/clean' });
  assert.throws(() => strictRouter.route({ vehicleId: 'v1', metric: 'unknown' }), /no route/);
});
