// Generated by Claude Code — CS 3660 Sprint 2
// Unit tests for the XState alert machine: state fold / reducer logic.
// Each test drives the machine through a specific transition path and
// asserts the resulting state. Uses sustainedReadings:1 for most tests
// to isolate individual transitions, then explicitly tests the
// sustain counter with sustainedReadings:3.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createActor } from 'xstate';
import { createAlertMachine } from '../src/alert-engine/alertMachine.js';

const BASE_CONFIG = {
  warnThreshold: 100,
  critThreshold: 110,
  hysteresisMargin: 5,
  sustainedReadings: 1,
  stalenessMs: 30000,
  lowIsBad: false,
};

function makeActor(overrides = {}) {
  const actor = createActor(createAlertMachine({ ...BASE_CONFIG, ...overrides }));
  actor.start();
  return actor;
}

function reading(value) {
  return { type: 'READING', value, ts: new Date().toISOString() };
}

// ---- NORMAL transitions ----

test('NORMAL -> WARNING on single warning reading (sustainedReadings:1)', () => {
  const actor = makeActor();
  actor.send(reading(105));
  assert.equal(actor.getSnapshot().value, 'WARNING');
});

test('NORMAL -> CRITICAL on single critical reading (sustainedReadings:1)', () => {
  const actor = makeActor();
  actor.send(reading(115));
  assert.equal(actor.getSnapshot().value, 'CRITICAL');
});

test('NORMAL stays NORMAL on reading within bounds', () => {
  const actor = makeActor();
  actor.send(reading(80));
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

// ---- WARNING transitions ----

test('WARNING -> CRITICAL on critical reading', () => {
  const actor = makeActor();
  actor.send(reading(105)); // -> WARNING
  actor.send(reading(115)); // -> CRITICAL
  assert.equal(actor.getSnapshot().value, 'CRITICAL');
});

test('WARNING -> NORMAL when reading clears hysteresis (below warnThreshold - margin)', () => {
  const actor = makeActor();
  actor.send(reading(105)); // -> WARNING
  actor.send(reading(90));  // below 100-5=95, isBackToNormal -> NORMAL
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

test('WARNING -> ACKNOWLEDGED on ACK', () => {
  const actor = makeActor();
  actor.send(reading(105));
  actor.send({ type: 'ACK', operator: 'test-ops' });
  assert.equal(actor.getSnapshot().value, 'ACKNOWLEDGED');
});

// ---- CRITICAL transitions ----

test('CRITICAL -> WARNING when reading drops into warning range', () => {
  const actor = makeActor();
  actor.send(reading(115)); // -> CRITICAL
  actor.send(reading(105)); // not critical, is warning -> WARNING
  assert.equal(actor.getSnapshot().value, 'WARNING');
});

test('CRITICAL -> ACKNOWLEDGED on ACK', () => {
  const actor = makeActor();
  actor.send(reading(115));
  actor.send({ type: 'ACK', operator: 'ops' });
  assert.equal(actor.getSnapshot().value, 'ACKNOWLEDGED');
});

// ---- ACKNOWLEDGED transitions ----

test('ACKNOWLEDGED -> CRITICAL on critical reading (re-escalation)', () => {
  const actor = makeActor();
  actor.send(reading(105)); // -> WARNING
  actor.send({ type: 'ACK' });
  actor.send(reading(115)); // -> CRITICAL
  assert.equal(actor.getSnapshot().value, 'CRITICAL');
});

test('ACKNOWLEDGED -> RESOLVED on sustained back-to-normal reading', () => {
  const actor = makeActor();
  actor.send(reading(105)); // -> WARNING
  actor.send({ type: 'ACK' });
  actor.send(reading(90)); // below hysteresis -> RESOLVED
  assert.equal(actor.getSnapshot().value, 'RESOLVED');
});

// ---- RESOLVED transitions ----

test('RESOLVED -> NORMAL on continued back-to-normal reading', () => {
  const actor = makeActor();
  actor.send(reading(105)); // -> WARNING
  actor.send({ type: 'ACK' });
  actor.send(reading(90));  // -> RESOLVED
  actor.send(reading(85));  // still below hysteresis -> NORMAL
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

// ---- OFFLINE transitions ----

test('NORMAL -> OFFLINE when HEARTBEAT_TIMEOUT fires with stale lastSeen', () => {
  const actor = makeActor({ stalenessMs: 1 }); // 1ms = always stale
  const staleTs = new Date(Date.now() - 5000).toISOString();
  actor.send({ type: 'READING', value: 80, ts: staleTs });
  actor.send({ type: 'HEARTBEAT_TIMEOUT' });
  assert.equal(actor.getSnapshot().value, 'OFFLINE');
});

test('WARNING -> OFFLINE when HEARTBEAT_TIMEOUT fires with stale lastSeen', () => {
  const actor = makeActor({ stalenessMs: 1 });
  const staleTs = new Date(Date.now() - 5000).toISOString();
  actor.send({ type: 'READING', value: 105, ts: staleTs }); // -> WARNING
  actor.send({ type: 'HEARTBEAT_TIMEOUT' });
  assert.equal(actor.getSnapshot().value, 'OFFLINE');
});

test('OFFLINE -> NORMAL on DEVICE_ONLINE', () => {
  const actor = makeActor({ stalenessMs: 1 });
  actor.send({ type: 'READING', value: 80, ts: new Date(Date.now() - 5000).toISOString() });
  actor.send({ type: 'HEARTBEAT_TIMEOUT' });
  assert.equal(actor.getSnapshot().value, 'OFFLINE');
  actor.send({ type: 'DEVICE_ONLINE' });
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

test('OFFLINE -> NORMAL on any READING', () => {
  const actor = makeActor({ stalenessMs: 1 });
  actor.send({ type: 'READING', value: 80, ts: new Date(Date.now() - 5000).toISOString() });
  actor.send({ type: 'HEARTBEAT_TIMEOUT' });
  actor.send(reading(80));
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

test('HEARTBEAT_TIMEOUT does not transition when lastSeen is recent', () => {
  const actor = makeActor({ stalenessMs: 30000 });
  actor.send(reading(80)); // lastSeen = now
  actor.send({ type: 'HEARTBEAT_TIMEOUT' });
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

// ---- Sustain counter ----

test('sustainedReadings:3 — stays NORMAL for first warning reading', () => {
  const actor = makeActor({ sustainedReadings: 3 });
  actor.send(reading(105));
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

test('sustainedReadings:3 — stays NORMAL for second consecutive warning reading', () => {
  const actor = makeActor({ sustainedReadings: 3 });
  actor.send(reading(105));
  actor.send(reading(105));
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

test('sustainedReadings:3 — transitions to WARNING on third consecutive warning reading', () => {
  const actor = makeActor({ sustainedReadings: 3 });
  actor.send(reading(105));
  actor.send(reading(105));
  actor.send(reading(105));
  assert.equal(actor.getSnapshot().value, 'WARNING');
});

test('sustain counter resets when a normal reading interrupts the sequence', () => {
  const actor = makeActor({ sustainedReadings: 3 });
  actor.send(reading(105)); // count=1
  actor.send(reading(80));  // normal: count resets to 0
  actor.send(reading(105)); // count=1
  actor.send(reading(105)); // count=2
  assert.equal(actor.getSnapshot().value, 'NORMAL'); // not yet at 3
});

// ---- lowIsBad (oilPressure / fuelLevel) ----

const LOW_IS_BAD = {
  warnThreshold: 25,
  critThreshold: 15,
  hysteresisMargin: 3,
  sustainedReadings: 1,
  stalenessMs: 30000,
  lowIsBad: true,
};

test('lowIsBad: NORMAL -> WARNING when value drops into warning range', () => {
  const actor = makeActor(LOW_IS_BAD);
  actor.send(reading(20)); // between critThreshold=15 and warnThreshold=25
  assert.equal(actor.getSnapshot().value, 'WARNING');
});

test('lowIsBad: NORMAL -> CRITICAL when value at or below critThreshold', () => {
  const actor = makeActor(LOW_IS_BAD);
  actor.send(reading(10)); // <= 15
  assert.equal(actor.getSnapshot().value, 'CRITICAL');
});

test('lowIsBad: normal high value stays NORMAL', () => {
  const actor = makeActor(LOW_IS_BAD);
  actor.send(reading(45)); // well above warnThreshold=25
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

test('lowIsBad: WARNING -> NORMAL when value recovers above warn + hysteresis', () => {
  const actor = makeActor(LOW_IS_BAD);
  actor.send(reading(20)); // -> WARNING
  actor.send(reading(30)); // above 25+3=28 -> NORMAL
  assert.equal(actor.getSnapshot().value, 'NORMAL');
});

// ---- Context tracking ----

test('context.lastValue updates on each reading', () => {
  const actor = makeActor();
  actor.send(reading(105));
  assert.equal(actor.getSnapshot().context.lastValue, 105);
  actor.send(reading(90));
  assert.equal(actor.getSnapshot().context.lastValue, 90);
});

test('context.consecutiveCount resets to 0 on state transition', () => {
  const actor = makeActor();
  actor.send(reading(105)); // -> WARNING, count resets to 0
  assert.equal(actor.getSnapshot().context.consecutiveCount, 0);
});

test('context.lastSeen is set to the reading timestamp', () => {
  const actor = makeActor();
  const ts = new Date().toISOString();
  actor.send({ type: 'READING', value: 80, ts });
  assert.equal(actor.getSnapshot().context.lastSeen, ts);
});
