// Generated by Claude Code — CS 3660 Sprint 2
// alert-panel: Lit Element component. Lists all channels currently in
// WARNING, CRITICAL, or ACKNOWLEDGED state with ACK and RESOLVE buttons.
// Emits custom 'alert-command' events that the parent page sends to the API.

import { LitElement, html, css } from 'lit';

const ACTIVE_STATES = new Set(['WARNING', 'CRITICAL', 'ACKNOWLEDGED']);

const STATE_COLOR = {
  WARNING:      '#f59e0b',
  CRITICAL:     '#ef4444',
  ACKNOWLEDGED: '#8b5cf6',
};

const METRIC_LABEL = {
  coolantTemp: 'Coolant Temp',
  oilPressure: 'Oil Pressure',
  rpm:         'RPM',
  fuelLevel:   'Fuel Level',
};

export class AlertPanel extends LitElement {
  static properties = {
    vehicles: { type: Object },
    token:    { type: String },
  };

  static styles = css`
    :host { display: block; font-family: system-ui, sans-serif; }

    h2 { margin: 0 0 1rem; font-size: 1rem; text-transform: uppercase;
         letter-spacing: .05em; color: #6b7280; }

    .empty { color: #6b7280; font-style: italic; }

    table { width: 100%; border-collapse: collapse; font-size: .875rem; }

    th {
      text-align: left; padding: .5rem .75rem;
      color: #9ca3af; font-weight: 500; border-bottom: 1px solid #374151;
    }

    td { padding: .5rem .75rem; color: #f9fafb; border-bottom: 1px solid #1f2937; }

    .state-badge {
      display: inline-block;
      padding: 2px 8px; border-radius: 9999px;
      font-size: .75rem; font-weight: 600; color: #fff;
    }

    .btn {
      padding: 3px 10px; border-radius: 4px; border: none;
      font-size: .75rem; font-weight: 600; cursor: pointer;
      margin-right: .25rem;
    }

    .btn-ack    { background: #8b5cf6; color: #fff; }
    .btn-resolve { background: #22c55e; color: #fff; }
    .btn:disabled { opacity: .4; cursor: not-allowed; }
  `;

  constructor() {
    super();
    this.vehicles = {};
    this.token    = '';
  }

  // Collect all active alert channels across all vehicles
  _activeAlerts() {
    const alerts = [];
    for (const [vehicleId, metrics] of Object.entries(this.vehicles ?? {})) {
      for (const [metric, data] of Object.entries(metrics)) {
        if (ACTIVE_STATES.has(data.state)) {
          alerts.push({ vehicleId, metric, ...data });
        }
      }
    }
    // Sort: CRITICAL first, then WARNING, then ACKNOWLEDGED
    const order = ['CRITICAL', 'WARNING', 'ACKNOWLEDGED'];
    alerts.sort((a, b) => order.indexOf(a.state) - order.indexOf(b.state));
    return alerts;
  }

  _sendCommand(type, vehicleId, metric) {
    this.dispatchEvent(new CustomEvent('alert-command', {
      bubbles: true,
      composed: true,
      detail: { type, vehicleId, metric },
    }));
  }

  _renderRow(alert) {
    const { vehicleId, metric, state, lastValue } = alert;
    const color  = STATE_COLOR[state] ?? '#6b7280';
    const label  = METRIC_LABEL[metric] ?? metric;
    const isAcked = state === 'ACKNOWLEDGED';
    return html`
      <tr>
        <td>${vehicleId}</td>
        <td>${label}</td>
        <td>
          <span class="state-badge" style="background:${color}">${state}</span>
        </td>
        <td>${lastValue != null ? lastValue.toFixed(1) : '--'}</td>
        <td>
          <button class="btn btn-ack"
            ?disabled=${isAcked}
            @click=${() => this._sendCommand('ACK', vehicleId, metric)}>
            ACK
          </button>
          <button class="btn btn-resolve"
            ?disabled=${!isAcked}
            @click=${() => this._sendCommand('RESOLVE', vehicleId, metric)}>
            Resolve
          </button>
        </td>
      </tr>
    `;
  }

  render() {
    const alerts = this._activeAlerts();
    return html`
      <h2>Active Alerts</h2>
      ${alerts.length === 0
        ? html`<p class="empty">No active alerts.</p>`
        : html`
          <table>
            <thead>
              <tr>
                <th>Vehicle</th>
                <th>Metric</th>
                <th>State</th>
                <th>Last Value</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              ${alerts.map(a => this._renderRow(a))}
            </tbody>
          </table>
        `
      }
    `;
  }
}

customElements.define('alert-panel', AlertPanel);
