// Generated by Claude Code — CS 3660 Sprint 2
// fleet-map: Lit Element component. Renders a live grid of vehicle cards,
// one card per vehicle, showing per-metric state and latest reading.
// Updates whenever the `vehicles` property is set by the parent page.

import { LitElement, html, css } from 'lit';

const STATE_COLOR = {
  NORMAL:       '#22c55e',
  WARNING:      '#f59e0b',
  CRITICAL:     '#ef4444',
  ACKNOWLEDGED: '#8b5cf6',
  RESOLVED:     '#6b7280',
  OFFLINE:      '#374151',
};

const METRIC_LABEL = {
  coolantTemp:  'Coolant',
  oilPressure:  'Oil PSI',
  rpm:          'RPM',
  fuelLevel:    'Fuel %',
};

const METRIC_UNIT = {
  coolantTemp: '°C',
  oilPressure: 'psi',
  rpm:         'rpm',
  fuelLevel:   '%',
};

export class FleetMap extends LitElement {
  static properties = {
    vehicles: { type: Object },
  };

  static styles = css`
    :host { display: block; font-family: system-ui, sans-serif; }

    h2 { margin: 0 0 1rem; font-size: 1rem; text-transform: uppercase;
         letter-spacing: .05em; color: #6b7280; }

    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
      gap: 1rem;
    }

    .card {
      background: #1f2937;
      border-radius: 8px;
      padding: 1rem;
      border: 1px solid #374151;
    }

    .card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: .75rem;
    }

    .vehicle-id { font-weight: 600; color: #f9fafb; font-size: .95rem; }

    .vehicle-dot {
      width: 10px; height: 10px; border-radius: 50%;
    }

    .metrics { display: flex; flex-direction: column; gap: .4rem; }

    .metric-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: .85rem;
    }

    .metric-name { color: #9ca3af; }

    .metric-value {
      display: flex;
      align-items: center;
      gap: .4rem;
    }

    .metric-number { color: #f9fafb; font-variant-numeric: tabular-nums; }

    .state-badge {
      font-size: .7rem;
      padding: 1px 6px;
      border-radius: 9999px;
      font-weight: 600;
      color: #fff;
    }

    .empty { color: #6b7280; font-style: italic; }
  `;

  constructor() {
    super();
    this.vehicles = {};
  }

  // Determine the worst state across all metrics for a vehicle (for the dot color)
  _worstState(metrics) {
    const order = ['OFFLINE', 'CRITICAL', 'WARNING', 'ACKNOWLEDGED', 'RESOLVED', 'NORMAL'];
    let worst = 'NORMAL';
    for (const { state } of Object.values(metrics)) {
      if (order.indexOf(state) < order.indexOf(worst)) worst = state;
    }
    return worst;
  }

  _renderMetric(metric, data) {
    const color = STATE_COLOR[data.state] ?? '#6b7280';
    const label = METRIC_LABEL[metric] ?? metric;
    const unit  = METRIC_UNIT[metric]  ?? '';
    const value = data.lastValue != null
      ? `${data.lastValue.toFixed(1)} ${unit}`
      : '--';
    return html`
      <div class="metric-row">
        <span class="metric-name">${label}</span>
        <span class="metric-value">
          <span class="metric-number">${value}</span>
          <span class="state-badge" style="background:${color}">${data.state}</span>
        </span>
      </div>
    `;
  }

  _renderCard(vehicleId, metrics) {
    const worst     = this._worstState(metrics);
    const dotColor  = STATE_COLOR[worst] ?? '#6b7280';
    return html`
      <div class="card">
        <div class="card-header">
          <span class="vehicle-id">${vehicleId}</span>
          <span class="vehicle-dot" style="background:${dotColor}" title="${worst}"></span>
        </div>
        <div class="metrics">
          ${Object.entries(metrics).map(([m, d]) => this._renderMetric(m, d))}
        </div>
      </div>
    `;
  }

  render() {
    const entries = Object.entries(this.vehicles ?? {});
    return html`
      <h2>Fleet</h2>
      ${entries.length === 0
        ? html`<p class="empty">No vehicles reporting yet.</p>`
        : html`<div class="grid">${entries.map(([id, m]) => this._renderCard(id, m))}</div>`
      }
    `;
  }
}

customElements.define('fleet-map', FleetMap);
