// Generated by Claude Code — CS 3660 Sprint 2
// XState v5 alert lifecycle state machine.
// One instance per monitored channel (e.g., vehicle-7:coolantTemp).
// States: NORMAL, WARNING, CRITICAL, ACKNOWLEDGED, RESOLVED, OFFLINE
// See CLAUDE.md for the full transition table and guard definitions.

import { createMachine, assign } from 'xstate';

/**
 * Create the alert machine for one channel.
 * @param {object} channelConfig
 * @param {boolean} [channelConfig.lowIsBad=false] - true for metrics where low values are dangerous
 */
export function createAlertMachine(channelConfig) {
  const {
    warnThreshold,
    critThreshold,
    hysteresisMargin = 5,
    sustainedReadings = 3,
    stalenessMs = 30000,
    lowIsBad = false,
  } = channelConfig;

  return createMachine({
    id: 'alertMachine',
    initial: 'NORMAL',
    context: {
      consecutiveCount: 0,
      lastSeen: null,
      lastValue: null,
    },
    states: {
      NORMAL: {
        on: {
          READING: [
            {
              guard: ({ context, event }) =>
                isCritical(event.value, critThreshold, lowIsBad) &&
                sustained(context.consecutiveCount + 1, sustainedReadings),
              target: 'CRITICAL',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              guard: ({ context, event }) =>
                isWarning(event.value, warnThreshold, critThreshold, lowIsBad) &&
                sustained(context.consecutiveCount + 1, sustainedReadings),
              target: 'WARNING',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              actions: assign({
                consecutiveCount: ({ context, event }) =>
                  meetsAnyCondition(event.value, warnThreshold, critThreshold, lowIsBad)
                    ? context.consecutiveCount + 1
                    : 0,
                lastSeen: ({ event }) => event.ts,
                lastValue: ({ event }) => event.value,
              }),
            },
          ],
          HEARTBEAT_TIMEOUT: {
            guard: ({ context }) => isStale(context.lastSeen, stalenessMs),
            target: 'OFFLINE',
          },
        },
      },

      WARNING: {
        on: {
          READING: [
            {
              guard: ({ context, event }) =>
                isCritical(event.value, critThreshold, lowIsBad) &&
                sustained(context.consecutiveCount + 1, sustainedReadings),
              target: 'CRITICAL',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              guard: ({ context, event }) =>
                isBackToNormal(event.value, warnThreshold, hysteresisMargin, lowIsBad) &&
                sustained(context.consecutiveCount + 1, sustainedReadings),
              target: 'NORMAL',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              actions: assign({
                consecutiveCount: ({ context }) => context.consecutiveCount + 1,
                lastSeen: ({ event }) => event.ts,
                lastValue: ({ event }) => event.value,
              }),
            },
          ],
          ACK: {
            guard: () => true,
            target: 'ACKNOWLEDGED',
          },
          HEARTBEAT_TIMEOUT: {
            guard: ({ context }) => isStale(context.lastSeen, stalenessMs),
            target: 'OFFLINE',
          },
        },
      },

      CRITICAL: {
        on: {
          READING: [
            {
              guard: ({ event }) =>
                !isCritical(event.value, critThreshold, lowIsBad) &&
                isWarning(event.value, warnThreshold, critThreshold, lowIsBad),
              target: 'WARNING',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              guard: ({ context, event }) =>
                isBackToNormal(event.value, warnThreshold, hysteresisMargin, lowIsBad) &&
                sustained(context.consecutiveCount + 1, sustainedReadings),
              target: 'NORMAL',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              actions: assign({
                consecutiveCount: ({ context }) => context.consecutiveCount + 1,
                lastSeen: ({ event }) => event.ts,
                lastValue: ({ event }) => event.value,
              }),
            },
          ],
          ACK: {
            target: 'ACKNOWLEDGED',
          },
          HEARTBEAT_TIMEOUT: {
            guard: ({ context }) => isStale(context.lastSeen, stalenessMs),
            target: 'OFFLINE',
          },
        },
      },

      ACKNOWLEDGED: {
        on: {
          READING: [
            {
              guard: ({ event }) => isCritical(event.value, critThreshold, lowIsBad),
              target: 'CRITICAL',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              guard: ({ context, event }) =>
                isBackToNormal(event.value, warnThreshold, hysteresisMargin, lowIsBad) &&
                sustained(context.consecutiveCount + 1, sustainedReadings),
              target: 'RESOLVED',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              actions: assign({
                consecutiveCount: ({ context }) => context.consecutiveCount + 1,
                lastSeen: ({ event }) => event.ts,
                lastValue: ({ event }) => event.value,
              }),
            },
          ],
          HEARTBEAT_TIMEOUT: {
            guard: ({ context }) => isStale(context.lastSeen, stalenessMs),
            target: 'OFFLINE',
          },
        },
      },

      RESOLVED: {
        on: {
          READING: [
            {
              guard: ({ event }) => isBackToNormal(event.value, warnThreshold, hysteresisMargin, lowIsBad),
              target: 'NORMAL',
              actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
            {
              guard: ({ event }) => meetsAnyCondition(event.value, warnThreshold, critThreshold, lowIsBad),
              target: 'WARNING',
              actions: assign({ consecutiveCount: 1, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
            },
          ],
        },
      },

      OFFLINE: {
        on: {
          DEVICE_ONLINE: {
            target: 'NORMAL',
            actions: assign({ consecutiveCount: 0 }),
          },
          READING: {
            target: 'NORMAL',
            actions: assign({ consecutiveCount: 0, lastSeen: ({ event }) => event.ts, lastValue: ({ event }) => event.value }),
          },
        },
      },
    },
  });
}

// ---- Guard functions (exported for unit testing) ----

export function isWarning(value, warnThreshold, critThreshold, lowIsBad = false) {
  if (lowIsBad) return value <= warnThreshold && value > critThreshold;
  return value >= warnThreshold && value < critThreshold;
}

export function isCritical(value, critThreshold, lowIsBad = false) {
  if (lowIsBad) return value <= critThreshold;
  return value >= critThreshold;
}

export function isBackToNormal(value, warnThreshold, hysteresisMargin, lowIsBad = false) {
  if (lowIsBad) return value > (warnThreshold + hysteresisMargin);
  return value < (warnThreshold - hysteresisMargin);
}

export function sustained(count, required) {
  return count >= required;
}

export function isStale(lastSeen, stalenessMs) {
  if (!lastSeen) return true;
  return (Date.now() - new Date(lastSeen).getTime()) > stalenessMs;
}

export function meetsAnyCondition(value, warnThreshold, critThreshold, lowIsBad = false) {
  if (lowIsBad) return value <= warnThreshold;
  return value >= warnThreshold;
}
