// Generated by Claude Code — CS 3660 Sprint 2
// Alert engine: subscribes to clean topics, runs XState machine per channel,
// dispatches domain events via EventDispatcher (Observer pattern).

import { createBusClient } from '../bus/mqttBus.js';
import { createAlertMachine } from './alertMachine.js';
import { createActor } from 'xstate';
import { createStrategy } from './StrategyFactory.js';
import { EventDispatcher } from '../events/EventDispatcher.js';
import { AuditLogger } from '../events/AuditLogger.js';
import { config } from '../config.js';

// Channel configs: one entry per metric type
const CHANNEL_CONFIGS = {
  coolantTemp: {
    warnThreshold: 100, critThreshold: 110,
    hysteresisMargin: 5, sustainedReadings: config.alertEngine.sustainedReadings,
    stalenessMs: config.alertEngine.stalenessMs,
    strategy: 'threshold',
  },
  oilPressure: {
    warnThreshold: 25, critThreshold: 15,
    hysteresisMargin: 3, sustainedReadings: config.alertEngine.sustainedReadings,
    stalenessMs: config.alertEngine.stalenessMs,
    strategy: 'threshold',
    lowIsBad: true,  // low oil pressure is dangerous
  },
  rpm: {
    warnThreshold: 3500, critThreshold: 4000,
    hysteresisMargin: 100, sustainedReadings: config.alertEngine.sustainedReadings,
    stalenessMs: config.alertEngine.stalenessMs,
    strategy: 'rollingAverage',
  },
  fuelLevel: {
    warnThreshold: 20, critThreshold: 10,
    hysteresisMargin: 2, sustainedReadings: config.alertEngine.sustainedReadings,
    stalenessMs: config.alertEngine.stalenessMs,
    strategy: 'rateOfChange',
    lowIsBad: true,  // low fuel level is dangerous
  },
};

const dispatcher = new EventDispatcher();
new AuditLogger(dispatcher); // Observer: writes every event to the store

// actors[channelKey] = XState actor
const actors = new Map();
// strategies[metric] = AlertStrategy instance
const strategies = {};
for (const [metric, cfg] of Object.entries(CHANNEL_CONFIGS)) {
  strategies[metric] = createStrategy(cfg.strategy);
}

function getOrCreateActor(vehicleId, metric) {
  const key = `${vehicleId}:${metric}`;
  if (!actors.has(key)) {
    const channelConfig = CHANNEL_CONFIGS[metric] ?? CHANNEL_CONFIGS.coolantTemp;
    const machine = createAlertMachine(channelConfig);
    const actor = createActor(machine);
    actor.subscribe((snapshot) => {
      // Emit a domain event on every state change
      dispatcher.dispatch('AlertStateChanged', {
        vehicleId, metric,
        aggregateId: key,
        state: snapshot.value,
        context: snapshot.context,
        ts: new Date().toISOString(),
      });
    });
    actor.start();
    actors.set(key, actor);
  }
  return actors.get(key);
}

async function main() {
  const client = await createBusClient('alert-engine-1', { clean: false });

  // Subscribe to LWT / device status for OFFLINE transitions
  client.subscribe('fleet/+/status', { qos: 1 });
  client.subscribe('fleet/+/+/clean', { qos: 1 });

  console.log('[alert-engine] subscribed to fleet/+/+/clean and fleet/+/status');

  client.on('message', (topic, buffer) => {
    let msg;
    try { msg = JSON.parse(buffer.toString()); }
    catch { return; }

    // Handle LWT / device status
    if (topic.match(/^fleet\/[^/]+\/status$/)) {
      const { vehicleId, status } = msg;
      if (status === 'offline') {
        for (const [key, actor] of actors) {
          if (key.startsWith(`${vehicleId}:`)) {
            actor.send({ type: 'HEARTBEAT_TIMEOUT' });
            dispatcher.dispatch('DeviceWentOffline', { vehicleId, ts: new Date().toISOString() });
          }
        }
      } else if (status === 'online') {
        for (const [key, actor] of actors) {
          if (key.startsWith(`${vehicleId}:`)) {
            actor.send({ type: 'DEVICE_ONLINE' });
          }
        }
      }
      return;
    }

    // Handle clean readings: fleet/{vehicleId}/{metric}/clean
    const { vehicleId, metric, value, ts } = msg;
    if (!vehicleId || !metric) return;

    const actor = getOrCreateActor(vehicleId, metric);
    actor.send({ type: 'READING', value, ts });

    dispatcher.dispatch('ReadingRecorded', {
      vehicleId, metric, value, ts,
      aggregateId: `${vehicleId}:${metric}`,
    });

    // Publish current alert state
    const state = actor.getSnapshot().value;
    client.publish(
      `alerts/${vehicleId}/${metric}`,
      JSON.stringify({ vehicleId, metric, state, value, ts }),
      { qos: 1, retain: true },
    );
  });

  // Heartbeat staleness check every 10s
  setInterval(() => {
    for (const [key, actor] of actors) {
      actor.send({ type: 'HEARTBEAT_TIMEOUT' });
    }
  }, 10000);
}

main().catch((err) => {
  console.error('[alert-engine] fatal:', err);
  process.exit(1);
});
  10000);
}

main().catch((err) => {
  console.error('[alert-engine] fatal:', err);
  process.exit(1);
});
