// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Factory Method (GoF) — StrategyFactory
// Builds the correct AlertStrategy for a given channel config.

import { ThresholdStrategy } from './strategies/ThresholdStrategy.js';
import { RollingAverageStrategy } from './strategies/RollingAverageStrategy.js';
import { RateOfChangeStrategy } from './strategies/RateOfChangeStrategy.js';

const STRATEGY_MAP = {
  threshold:     () => new ThresholdStrategy(),
  rollingAverage: () => new RollingAverageStrategy(),
  rateOfChange:  () => new RateOfChangeStrategy(),
};

/**
 * Create the alert evaluation strategy for a channel.
 *
 * @param {string} strategyName - 'threshold' | 'rollingAverage' | 'rateOfChange'
 * @returns {import('./strategies/AlertStrategy.js').AlertStrategy}
 */
export function createStrategy(strategyName) {
  const factory = STRATEGY_MAP[strategyName];
  if (!factory) {
    throw new Error(`StrategyFactory: unknown strategy "${strategyName}". Known: ${Object.keys(STRATEGY_MAP).join(', ')}`);
  }
  return factory();
}
