// Generated by Claude Code — CS 3660 Sprint 2
// Device simulator: publishes raw sensor readings for multiple vehicles.
// Supports scripted threshold crossings and intentional disconnects for demo purposes.
//
// Topic: fleet/{vehicleId}/raw
// Payload: { vehicleId, metric, value, unit, ts }
//
// Usage: node src/device-sim/index.js
// Set VEHICLE_IDS env var to a comma-separated list (default: vehicle-1,vehicle-2,vehicle-3)
// Set PUBLISH_INTERVAL_MS to control publish frequency (default: 2000)

import { createBusClient } from '../bus/mqttBus.js';

const VEHICLE_IDS = (process.env.VEHICLE_IDS ?? 'vehicle-1,vehicle-2,vehicle-3').split(',');
const INTERVAL_MS = parseInt(process.env.PUBLISH_INTERVAL_MS ?? '2000', 10);

// Metric definitions: name, unit, baseline, range (baseline +/- range * noise)
const METRICS = [
  { name: 'coolantTemp', unit: 'C',   baseline: 85,  range: 10  },
  { name: 'oilPressure', unit: 'psi', baseline: 45,  range: 8   },
  { name: 'rpm',         unit: 'rpm', baseline: 2200, range: 400 },
  { name: 'fuelLevel',   unit: '%',   baseline: 70,  range: 5   },
];

// Per-vehicle state to allow scripted spikes
const vehicleState = {};
for (const id of VEHICLE_IDS) {
  vehicleState[id] = { spike: null, tick: 0 };
}

function readingValue(metric, state) {
  const noise = (Math.random() - 0.5) * 2 * metric.range * 0.2;
  if (state.spike && state.spike.metric === metric.name) {
    return state.spike.value + noise;
  }
  return metric.baseline + noise;
}

async function main() {
  const clients = {};

  for (const vehicleId of VEHICLE_IDS) {
    const client = await createBusClient(`device-sim-${vehicleId}`, {
      clean: true,
      will: {
        topic: `fleet/${vehicleId}/status`,
        payload: JSON.stringify({ vehicleId, status: 'offline', ts: new Date().toISOString() }),
        qos: 1,
        retain: true,
      },
    });
    clients[vehicleId] = client;
    console.log(`[device-sim] ${vehicleId} ready`);
  }

  // Publish a retained online status for each vehicle
  for (const vehicleId of VEHICLE_IDS) {
    clients[vehicleId].publish(
      `fleet/${vehicleId}/status`,
      JSON.stringify({ vehicleId, status: 'online', ts: new Date().toISOString() }),
      { qos: 1, retain: true },
    );
  }

  setInterval(() => {
    for (const vehicleId of VEHICLE_IDS) {
      const state = vehicleState[vehicleId];
      state.tick++;

      for (const metric of METRICS) {
        const value = readingValue(metric, state);
        const payload = {
          vehicleId,
          metric: metric.name,
          value: parseFloat(value.toFixed(2)),
          unit: metric.unit,
          ts: new Date().toISOString(),
        };

        clients[vehicleId].publish(
          `fleet/${vehicleId}/raw`,
          JSON.stringify(payload),
          { qos: 0, retain: false },
          (err) => {
            if (err) console.error(`[device-sim] publish error for ${vehicleId}:`, err.message);
          },
        );
      }
    }
  }, INTERVAL_MS);

  // Allow external scripting: expose vehicleState for manual spike injection
  // e.g. vehicleState['vehicle-1'].spike = { metric: 'coolantTemp', value: 115 }
  global.vehicleState = vehicleState;

  console.log(`[device-sim] publishing ${VEHICLE_IDS.length} vehicles every ${INTERVAL_MS}ms`);
}

main().catch((err) => {
  console.error('[device-sim] fatal:', err);
  process.exit(1);
});
