// Generated by Claude Code — CS 3660 Sprint 2
// Observer: AuditLogger
// Registered with EventDispatcher. Appends every domain event to the event store.

import { appendEvent } from './eventStore.js';

export class AuditLogger {
  constructor(dispatcher) {
    dispatcher.subscribe('*', this.onEvent.bind(this));
  }

  onEvent(eventType, payload) {
    try {
      appendEvent({
        aggregateType:  payload.aggregateType ?? 'channel',
        aggregateId:    payload.aggregateId   ?? `${payload.vehicleId}:${payload.metric}`,
        eventType,
        payload,
        occurredAt:     payload.ts ?? new Date().toISOString(),
        actor:          payload.actor ?? 'system',
        correlationId:  payload.correlationId ?? null,
        causationId:    payload.causationId   ?? null,
      });
    } catch (err) {
      console.error('[AuditLogger] failed to append event:', err.message);
    }
  }
}
