// Generated by Claude Code — CS 3660 Sprint 2
// Append-only event store using better-sqlite3.
// Core rule: domain state is NEVER updated in place. Every mutation is an
// immutable, append-only event. Read models are projections derived by folding.

import Database from 'better-sqlite3';
import { createHash } from 'crypto';
import { mkdirSync } from 'fs';
import { dirname } from 'path';
import { config } from '../config.js';

let db;

function getDb() {
  if (!db) {
    mkdirSync(dirname(config.sqlitePath), { recursive: true });
    db = new Database(config.sqlitePath);
    db.pragma('journal_mode = WAL');
    db.pragma('foreign_keys = ON');
    initSchema(db);
  }
  return db;
}

function initSchema(db) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS events (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      aggregate_type  TEXT    NOT NULL,
      aggregate_id    TEXT    NOT NULL,
      event_type      TEXT    NOT NULL,
      payload         TEXT    NOT NULL,
      occurred_at     TEXT    NOT NULL,
      recorded_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
      actor           TEXT    NOT NULL DEFAULT 'system',
      correlation_id  TEXT,
      causation_id    TEXT,
      prev_hash       TEXT    NOT NULL DEFAULT '',
      hash            TEXT    NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_events_aggregate ON events (aggregate_type, aggregate_id, id);
    CREATE INDEX IF NOT EXISTS idx_events_occurred  ON events (occurred_at);
  `);
}

export function appendEvent(event) {
  const database = getDb();

  const append = database.transaction((e) => {
    const last = database
      .prepare('SELECT hash FROM events WHERE aggregate_type = ? AND aggregate_id = ? ORDER BY id DESC LIMIT 1')
      .get(e.aggregateType, e.aggregateId);

    const prevHash = last?.hash ?? '';
    const canonical = JSON.stringify({ prevHash, payload: e.payload });
    const hash = createHash('sha256').update(canonical).digest('hex');

    const stmt = database.prepare(`
      INSERT INTO events
        (aggregate_type, aggregate_id, event_type, payload, occurred_at, actor, correlation_id, causation_id, prev_hash, hash)
      VALUES
        (@aggregateType, @aggregateId, @eventType, @payload, @occurredAt, @actor, @correlationId, @causationId, @prevHash, @hash)
    `);

    const result = stmt.run({
      aggregateType: e.aggregateType,
      aggregateId:   e.aggregateId,
      eventType:     e.eventType,
      payload:       JSON.stringify(e.payload),
      occurredAt:    e.occurredAt ?? new Date().toISOString(),
      actor:         e.actor ?? 'system',
      correlationId: e.correlationId ?? null,
      causationId:   e.causationId ?? null,
      prevHash,
      hash,
    });

    return result.lastInsertRowid;
  });

  return append(event);
}

export function getEvents(aggregateType, aggregateId, { upToTime } = {}) {
  const database = getDb();
  if (upToTime) {
    return database
      .prepare('SELECT * FROM events WHERE aggregate_type = ? AND aggregate_id = ? AND occurred_at <= ? ORDER BY id')
      .all(aggregateType, aggregateId, upToTime);
  }
  return database
    .prepare('SELECT * FROM events WHERE aggregate_type = ? AND aggregate_id = ? ORDER BY id')
    .all(aggregateType, aggregateId);
}

export function verifyChain(aggregateType, aggregateId) {
  const events = getEvents(aggregateType, aggregateId);
  let prevHash = '';
  for (const e of events) {
    const canonical = JSON.stringify({ prevHash, payload: JSON.parse(e.payload) });
    const expected = createHash('sha256').update(canonical).digest('hex');
    if (expected !== e.hash) return false;
    prevHash = e.hash;
  }
  return true;
}

export function getAllEvents({ upToTime } = {}) {
  const database = getDb();
  if (upToTime) {
    return database
      .prepare('SELECT * FROM events WHERE occurred_at <= ? ORDER BY id')
      .all(upToTime);
  }
  return database.prepare('SELECT * FROM events ORDER BY id').all();
}
