// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Observer (GoF)
// Reference: Gamma et al., Design Patterns (1994)
//
// In-process domain-event dispatcher. The alert-engine produces domain events
// (state transitions, readings accepted) and notifies all registered observers.
// This is the GoF Observer in process — distinct from the cross-process
// Publish-Subscribe EIP on MQTT. The distinction matters: MQTT pub-sub handles
// cross-component messaging; Observer handles in-process fan-out within a single
// component, decoupling the alert-engine from logging and WebSocket concerns.

export class EventDispatcher {
  constructor() {
    /** @type {Map<string, Set<Function>>} */
    this.listeners = new Map();
  }

  /**
   * Register an observer for one or more event types.
   * Use '*' to observe all event types.
   *
   * @param {string|string[]} eventTypes
   * @param {Function} observer - Called with (eventType, payload)
   */
  subscribe(eventTypes, observer) {
    const types = Array.isArray(eventTypes) ? eventTypes : [eventTypes];
    for (const type of types) {
      if (!this.listeners.has(type)) this.listeners.set(type, new Set());
      this.listeners.get(type).add(observer);
    }
  }

  /**
   * Remove an observer.
   */
  unsubscribe(eventTypes, observer) {
    const types = Array.isArray(eventTypes) ? eventTypes : [eventTypes];
    for (const type of types) {
      this.listeners.get(type)?.delete(observer);
    }
  }

  /**
   * Dispatch a domain event to all registered observers.
   *
   * @param {string} eventType
   * @param {object} payload
   */
  dispatch(eventType, payload) {
    const specific = this.listeners.get(eventType);
    const wildcard = this.listeners.get('*');

    if (specific) {
      for (const observer of specific) {
        try { observer(eventType, payload); }
        catch (err) { console.error(`[EventDispatcher] observer error (${eventType}):`, err.message); }
      }
    }
    if (wildcard) {
      for (const observer of wildcard) {
        try { observer(eventType, payload); }
        catch (err) { console.error(`[EventDispatcher] wildcard observer error:`, err.message); }
      }
    }
  }
}
