// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Observer (GoF)
// Reference: Gamma et al., Design Patterns (1994)

export class EventDispatcher {
  constructor() {
    this.listeners = new Map();
  }

  subscribe(eventTypes, observer) {
    const types = Array.isArray(eventTypes) ? eventTypes : [eventTypes];
    for (const type of types) {
      if (!this.listeners.has(type)) this.listeners.set(type, new Set());
      this.listeners.get(type).add(observer);
    }
  }

  unsubscribe(eventTypes, observer) {
    const types = Array.isArray(eventTypes) ? eventTypes : [eventTypes];
    for (const type of types) {
      this.listeners.get(type)?.delete(observer);
    }
  }

  dispatch(eventType, payload) {
    const specific = this.listeners.get(eventType);
    const wildcard = this.listeners.get('*');

    if (specific) {
      for (const observer of specific) {
        try { observer(eventType, payload); }
        catch (err) { console.error(`[EventDispatcher] observer error (${eventType}):`, err.message); }
      }
    }
    if (wildcard) {
      for (const observer of wildcard) {
        try { observer(eventType, payload); }
        catch (err) { console.error('[EventDispatcher] wildcard observer error:', err.message); }
      }
    }
  }
}
