// Generated by Claude Code — CS 3660 Sprint 2
// Observer: WsBridgeObserver
// Registered with EventDispatcher. Forwards domain events to all connected
// WebSocket clients so the dashboard sees transitions in real time.

export class WsBridgeObserver {
  constructor(dispatcher, broadcast) {
    this.broadcast = broadcast;
    dispatcher.subscribe('*', this.onEvent.bind(this));
  }

  onEvent(eventType, payload) {
    try {
      this.broadcast(JSON.stringify({ eventType, payload, sentAt: new Date().toISOString() }));
    } catch (err) {
      console.error('[WsBridgeObserver] broadcast error:', err.message);
    }
  }
}
