// Generated by Claude Code — CS 3660 Sprint 2
// inject-spike.js: publishes fake raw readings above the critical threshold
// for vehicle-1 coolantTemp so the full pipeline produces a CRITICAL alert.
//
// Usage:
//   node scripts/inject-spike.js          -- injects 5 CRITICAL readings
//   node scripts/inject-spike.js clear    -- injects 5 NORMAL readings to resolve

import { createBusClient } from '../src/bus/mqttBus.js';

const MODE   = process.argv[2] === 'clear' ? 'clear' : 'spike';
const VALUE  = MODE === 'spike' ? 115 : 82;   // 115 = CRITICAL, 82 = well below hysteresis
const LABEL  = MODE === 'spike' ? 'CRITICAL spike' : 'NORMAL clear';
const COUNT  = 5;
const DELAY  = 400;  // fast: all 5 arrive before device-sim can interleave a normal reading

const client = await createBusClient(`inject-spike-${Date.now()}`, { clean: true });

console.log(`[inject-spike] sending ${COUNT} ${LABEL} readings for vehicle-1/coolantTemp...`);

for (let i = 0; i < COUNT; i++) {
  await new Promise(r => setTimeout(r, i === 0 ? 0 : DELAY));
  const payload = {
    vehicleId: 'vehicle-1',
    metric: 'coolantTemp',
    value: VALUE + (Math.random() - 0.5) * 0.5,
    unit: 'C',
    ts: new Date().toISOString(),
  };
  client.publish('fleet/vehicle-1/raw', JSON.stringify(payload), { qos: 0 });
  console.log(`[inject-spike] ${i + 1}/${COUNT}  value=${payload.value.toFixed(2)}`);
}

// Give the last message time to propagate then exit cleanly
setTimeout(() => {
  client.end();
  console.log('[inject-spike] done. Watch the dashboard for state change.');
}, 1000);
