// Generated by Claude Code — CS 3660 Sprint 2
// ws-bridge: Koa HTTP server + WebSocket server.
//
// Responsibilities:
//   1. Serve the dashboard SPA from /dashboard
//   2. Bridge MQTT -> browser over wss:// (WebSocket)
//   3. Send current fleet state to each client on connect (catch-up)
//   4. GET  /api/fleet-state?upToTime=<iso>  — point-in-time reconstruction
//   5. POST /api/command  { type, vehicleId, metric, operator }  — ACK / RESOLVE
//      Requires Authorization: Bearer <token> header

import Koa from 'koa';
import Router from 'koa-router';
import { createServer } from 'http';
import { WebSocketServer } from 'ws';
import { createReadStream, existsSync } from 'fs';
import { join, extname } from 'path';
import { fileURLToPath } from 'url';
import { createBusClient } from '../bus/mqttBus.js';
import { getAllEvents } from '../events/eventStore.js';
import { config } from '../config.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const DASHBOARD_DIR = join(__dirname, '../../dashboard');

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.ico':  'image/x-icon',
};

function reconstructFleetState(upToTime) {
  const events = getAllEvents(upToTime ? { upToTime } : {});
  const fleet = {};
  for (const row of events) {
    let payload;
    try { payload = JSON.parse(row.payload); } catch { continue; }
    const { vehicleId, metric } = payload;
    if (!vehicleId || !metric) continue;
    if (!fleet[vehicleId]) fleet[vehicleId] = {};
    if (!fleet[vehicleId][metric]) {
      fleet[vehicleId][metric] = { state: 'NORMAL', lastValue: null, lastSeen: null };
    }
    if (row.event_type === 'AlertStateChanged') {
      fleet[vehicleId][metric].state = payload.state;
    } else if (row.event_type === 'ReadingRecorded') {
      fleet[vehicleId][metric].lastValue = payload.value;
      fleet[vehicleId][metric].lastSeen  = payload.ts;
    }
  }
  return fleet;
}

async function readBody(ctx) {
  return new Promise((resolve) => {
    let raw = '';
    ctx.req.on('data', chunk => raw += chunk);
    ctx.req.on('end', () => { try { resolve(JSON.parse(raw)); } catch { resolve({}); } });
    ctx.req.on('error', () => resolve({}));
  });
}

function requireAuth(ctx) {
  const header = ctx.headers['authorization'] ?? '';
  const token  = header.startsWith('Bearer ') ? header.slice(7) : '';
  return token === config.authToken;
}

// ---- WebSocket client set (module-level so MQTT handler can access it) ----
const clients = new Set();

function broadcast(obj) {
  const msg = JSON.stringify(obj);
  for (const ws of clients) {
    if (ws.readyState === 1) ws.send(msg);
  }
}

// ---- MQTT connection (non-fatal — HTTP server starts regardless) ----
let mqttClient = null;

async function connectMqtt(attempt = 1) {
  try {
    mqttClient = await createBusClient(`ws-bridge-${Date.now()}`, { clean: true });
    mqttClient.subscribe(['alerts/#', 'fleet/#'], { qos: 1 });
    console.log('[ws-bridge] MQTT connected, subscribed to alerts/# and fleet/#');

    mqttClient.on('message', (topic, buffer) => {
      let payload;
      try { payload = JSON.parse(buffer.toString()); } catch { return; }
      broadcast({ type: 'mqtt', topic, payload, ts: new Date().toISOString() });
    });

    mqttClient.on('error', (err) => {
      console.error('[ws-bridge] MQTT error:', err.message);
    });
  } catch (err) {
    const delay = Math.min(30000, attempt * 5000);
    console.error(`[ws-bridge] MQTT connection failed (attempt ${attempt}): ${err.message}. Retrying in ${delay / 1000}s`);
    setTimeout(() => connectMqtt(attempt + 1), delay);
  }
}

async function main() {
  // ---- Koa app ----
  const app    = new Koa();
  const router = new Router();

  router.get('/api/fleet-state', (ctx) => {
    ctx.body = reconstructFleetState(ctx.query.upToTime ?? null);
  });

  router.get('/api/events/range', (ctx) => {
    const all = getAllEvents();
    ctx.body = all.length === 0
      ? { earliest: null, latest: null }
      : { earliest: all[0].occurred_at, latest: all[all.length - 1].occurred_at };
  });

  router.get('/health', (ctx) => {
    ctx.body = { status: 'ok', mqtt: mqttClient?.connected ?? false };
  });

  router.post('/api/command', async (ctx) => {
    if (!requireAuth(ctx)) { ctx.status = 401; ctx.body = { error: 'Unauthorized' }; return; }
    const { type, vehicleId, metric, operator = 'operator' } = await readBody(ctx);
    if (!type || !vehicleId || !metric) { ctx.status = 400; ctx.body = { error: 'type, vehicleId, and metric are required' }; return; }
    if (type !== 'ACK' && type !== 'RESOLVE') { ctx.status = 400; ctx.body = { error: 'type must be ACK or RESOLVE' }; return; }
    if (!mqttClient?.connected) { ctx.status = 503; ctx.body = { error: 'MQTT not connected' }; return; }
    mqttClient.publish(
      `fleet/${vehicleId}/${metric}/command`,
      JSON.stringify({ type, vehicleId, metric, operator, ts: new Date().toISOString() }),
      { qos: 1 },
    );
    ctx.body = { ok: true };
  });

  router.get('/dashboard/(.*)', async (ctx) => {
    const rel  = ctx.params[0] || 'index.html';
    const file = join(DASHBOARD_DIR, rel);
    if (!existsSync(file)) { ctx.status = 404; return; }
    ctx.type = MIME[extname(file)] ?? 'application/octet-stream';
    ctx.body = createReadStream(file);
  });

  router.get('/', (ctx) => { ctx.redirect('/dashboard/'); });

  app.use(router.routes()).use(router.allowedMethods());

  // ---- HTTP + WebSocket server ----
  const httpServer = createServer(app.callback());
  const wss = new WebSocketServer({ server: httpServer, path: '/ws' });

  wss.on('connection', (ws) => {
    clients.add(ws);
    console.log(`[ws-bridge] client connected (total: ${clients.size})`);
    ws.send(JSON.stringify({ type: 'fleet-state', payload: reconstructFleetState() }));
    ws.on('close', () => { clients.delete(ws); console.log(`[ws-bridge] client disconnected (total: ${clients.size})`); });
    ws.on('error', (err) => console.error('[ws-bridge] ws error:', err.message));
  });

  httpServer.listen(config.wsBridge.port, () => {
    console.log(`[ws-bridge] listening on port ${config.wsBridge.port}`);
    console.log(`[ws-bridge] dashboard at http://localhost:${config.wsBridge.port}/dashboard/`);
  });

  // Connect to MQTT in background — server stays up even if broker is unreachable
  connectMqtt();
}

main().catch((err) => {
  console.error('[ws-bridge] fatal:', err);
  process.exit(1);
});
