// Generated by Claude Code — CS 3660 Sprint 2
// ws-bridge: Koa HTTP server + WebSocket server.
//
// Responsibilities:
//   1. Serve the dashboard SPA from /dashboard
//   2. Bridge MQTT -> browser over wss:// (WebSocket)
//   3. Send current fleet state to each client on connect (catch-up)
//   4. GET  /api/fleet-state?upToTime=<iso>  — point-in-time reconstruction
//   5. POST /api/command  { type, vehicleId, metric, operator }  — ACK / RESOLVE
//      Requires Authorization: Bearer <token> header
//
// The browser speaks wss:// to this bridge. The bridge speaks plain MQTT to
// the broker. This is required because browsers served over HTTPS cannot open
// plain ws:// connections to an external broker.

import Koa from 'koa';
import Router from 'koa-router';
import { createServer } from 'http';
import { WebSocketServer } from 'ws';
import { createReadStream, existsSync } from 'fs';
import { join, extname } from 'path';
import { fileURLToPath } from 'url';
import { createBusClient } from '../bus/mqttBus.js';
import { getAllEvents } from '../events/eventStore.js';
import { config } from '../config.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const DASHBOARD_DIR = join(__dirname, '../../dashboard');

// ---- MIME types for static file serving ----
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.ico':  'image/x-icon',
};

// ---- Fleet state reconstruction (pure projection over event store) ----
// Folds all events up to an optional timestamp into a current-state snapshot.
// Only AlertStateChanged and ReadingRecorded events affect the projection.
function reconstructFleetState(upToTime) {
  const events = getAllEvents(upToTime ? { upToTime } : {});
  const fleet = {};
  for (const row of events) {
    let payload;
    try { payload = JSON.parse(row.payload); } catch { continue; }
    const { vehicleId, metric } = payload;
    if (!vehicleId || !metric) continue;
    if (!fleet[vehicleId]) fleet[vehicleId] = {};
    if (!fleet[vehicleId][metric]) {
      fleet[vehicleId][metric] = { state: 'NORMAL', lastValue: null, lastSeen: null };
    }
    if (row.event_type === 'AlertStateChanged') {
      fleet[vehicleId][metric].state = payload.state;
    } else if (row.event_type === 'ReadingRecorded') {
      fleet[vehicleId][metric].lastValue = payload.value;
      fleet[vehicleId][metric].lastSeen  = payload.ts;
    }
  }
  return fleet;
}

// ---- Body reader (avoids needing koa-bodyparser) ----
async function readBody(ctx) {
  return new Promise((resolve) => {
    let raw = '';
    ctx.req.on('data', chunk => raw += chunk);
    ctx.req.on('end', () => {
      try { resolve(JSON.parse(raw)); } catch { resolve({}); }
    });
    ctx.req.on('error', () => resolve({}));
  });
}

// ---- Auth middleware for mutation endpoints ----
function requireAuth(ctx) {
  const header = ctx.headers['authorization'] ?? '';
  const token  = header.startsWith('Bearer ') ? header.slice(7) : '';
  return token === config.authToken;
}

async function main() {
  // ---- MQTT client ----
  const mqttClient = await createBusClient(`ws-bridge-${Date.now()}`, { clean: true });
  mqttClient.subscribe(['alerts/#', 'fleet/#'], { qos: 1 });
  console.log('[ws-bridge] MQTT subscribed to alerts/# and fleet/#');

  // ---- WebSocket clients ----
  const clients = new Set();

  function broadcast(obj) {
    const msg = JSON.stringify(obj);
    for (const ws of clients) {
      if (ws.readyState === 1 /* OPEN */) ws.send(msg);
    }
  }

  // Forward every MQTT message to connected browsers
  mqttClient.on('message', (topic, buffer) => {
    let payload;
    try { payload = JSON.parse(buffer.toString()); } catch { return; }
    broadcast({ type: 'mqtt', topic, payload, ts: new Date().toISOString() });
  });

  // ---- Koa app ----
  const app    = new Koa();
  const router = new Router();

  // GET /api/fleet-state — reconstruct fleet at an optional point in time
  router.get('/api/fleet-state', (ctx) => {
    const upToTime = ctx.query.upToTime ?? null;
    ctx.body = reconstructFleetState(upToTime);
  });

  // GET /api/events/range — time range of stored events (for slider bounds)
  router.get('/api/events/range', (ctx) => {
    const all = getAllEvents();
    if (all.length === 0) {
      ctx.body = { earliest: null, latest: null };
    } else {
      ctx.body = {
        earliest: all[0].occurred_at,
        latest:   all[all.length - 1].occurred_at,
      };
    }
  });

  // POST /api/command — ACK or RESOLVE an alert channel
  router.post('/api/command', async (ctx) => {
    if (!requireAuth(ctx)) {
      ctx.status = 401;
      ctx.body   = { error: 'Unauthorized' };
      return;
    }
    const { type, vehicleId, metric, operator = 'operator' } = await readBody(ctx);
    if (!type || !vehicleId || !metric) {
      ctx.status = 400;
      ctx.body   = { error: 'type, vehicleId, and metric are required' };
      return;
    }
    if (type !== 'ACK' && type !== 'RESOLVE') {
      ctx.status = 400;
      ctx.body   = { error: 'type must be ACK or RESOLVE' };
      return;
    }
    // Publish command to MQTT. The alert-engine subscribes and forwards to
    // the correct XState actor.
    mqttClient.publish(
      `fleet/${vehicleId}/${metric}/command`,
      JSON.stringify({ type, vehicleId, metric, operator, ts: new Date().toISOString() }),
      { qos: 1 },
    );
    ctx.body = { ok: true };
  });

  // Static file serving for the dashboard SPA
  router.get('/dashboard/(.*)', async (ctx) => {
    const rel  = ctx.params[0] || 'index.html';
    const file = join(DASHBOARD_DIR, rel);
    if (!existsSync(file)) { ctx.status = 404; return; }
    ctx.type = MIME[extname(file)] ?? 'application/octet-stream';
    ctx.body = createReadStream(file);
  });

  // Root redirects to dashboard
  router.get('/', (ctx) => { ctx.redirect('/dashboard/'); });

  app.use(router.routes()).use(router.allowedMethods());

  // ---- HTTP + WebSocket server ----
  const httpServer = createServer(app.callback());
  const wss = new WebSocketServer({ server: httpServer, path: '/ws' });

  wss.on('connection', (ws) => {
    clients.add(ws);
    console.log(`[ws-bridge] client connected (total: ${clients.size})`);

    // Send current fleet state immediately so the client doesn't start blank
    const currentState = reconstructFleetState();
    ws.send(JSON.stringify({ type: 'fleet-state', payload: currentState }));

    ws.on('close', () => {
      clients.delete(ws);
      console.log(`[ws-bridge] client disconnected (total: ${clients.size})`);
    });
    ws.on('error', (err) => console.error('[ws-bridge] ws error:', err.message));
  });

  httpServer.listen(config.wsBridge.port, () => {
    console.log(`[ws-bridge] listening on http://localhost:${config.wsBridge.port}`);
    console.log(`[ws-bridge] dashboard at http://localhost:${config.wsBridge.port}/dashboard/`);
  });
}

main().catch((err) => {
  console.error('[ws-bridge] fatal:', err);
  process.exit(1);
});
