// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Strategy (GoF) — base interface
// Reference: Gamma et al., Design Patterns (1994)
//
// AlertStrategy defines the interface that all concrete strategies must implement.
// The alert-engine selects a strategy per channel and calls evaluate() on each
// incoming reading. This makes the evaluation algorithm interchangeable at runtime.

export class AlertStrategy {
  /**
   * Evaluate a reading and return whether it triggers an alert state.
   *
   * @param {object} enrichedMessage - Enriched message from the gateway.
   * @param {object} channelConfig   - Per-channel config (thresholds, etc.).
   * @returns {{ isWarning: boolean, isCritical: boolean, reason: string }}
   */
  evaluate(enrichedMessage, channelConfig) { // eslint-disable-line no-unused-vars
    throw new Error('AlertStrategy.evaluate() must be implemented by subclass');
  }
}
