// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Strategy (GoF) — RateOfChangeStrategy
// Detects sudden drops or spikes (e.g. fuelLevel sudden drop = possible siphon/leak).
// Compares the current value to the previous reading and checks if the delta
// exceeds the configured rate threshold.

import { AlertStrategy } from './AlertStrategy.js';

export class RateOfChangeStrategy extends AlertStrategy {
  constructor() {
    super();
    // previous[channelKey] = last value
    this.previous = new Map();
  }

  evaluate(enrichedMessage, channelConfig) {
    const { vehicleId, metric, value } = enrichedMessage;
    const { rateWarnThreshold = 10, rateCritThreshold = 20 } = channelConfig;

    const key = `${vehicleId}:${metric}`;
    const prev = this.previous.get(key);
    this.previous.set(key, value);

    if (prev === undefined) {
      // No history yet — cannot evaluate rate
      return { isWarning: false, isCritical: false, reason: 'no previous reading' };
    }

    const delta = Math.abs(value - prev);
    const isCritical = delta >= rateCritThreshold;
    const isWarning  = !isCritical && delta >= rateWarnThreshold;

    return {
      isWarning,
      isCritical,
      reason: isCritical
        ? `rate of change ${delta.toFixed(2)} >= critical rate threshold ${rateCritThreshold}`
        : isWarning
        ? `rate of change ${delta.toFixed(2)} >= warning rate threshold ${rateWarnThreshold}`
        : `rate of change ${delta.toFixed(2)} within bounds`,
    };
  }
}
