// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Strategy (GoF) — RollingAverageStrategy
// Evaluates the rolling average (provided by ContentEnricher) against thresholds.
// Smooths out noisy spikes by requiring a sustained elevated average.

import { AlertStrategy } from './AlertStrategy.js';

export class RollingAverageStrategy extends AlertStrategy {
  evaluate(enrichedMessage, channelConfig) {
    const value = enrichedMessage.rollingAvg ?? enrichedMessage.value;
    const { warnThreshold, critThreshold } = channelConfig;

    const isCritical = value >= critThreshold;
    const isWarning  = !isCritical && value >= warnThreshold;

    return {
      isWarning,
      isCritical,
      reason: isCritical
        ? `rolling avg ${value.toFixed(2)} >= critical threshold ${critThreshold}`
        : isWarning
        ? `rolling avg ${value.toFixed(2)} >= warning threshold ${warnThreshold}`
        : `rolling avg ${value.toFixed(2)} within bounds`,
    };
  }
}
