// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Strategy (GoF) — ThresholdStrategy
// Evaluates a reading against static warn/critical thresholds.
// Used for: coolantTemp, oilPressure, rpm.

import { AlertStrategy } from './AlertStrategy.js';

export class ThresholdStrategy extends AlertStrategy {
  evaluate(enrichedMessage, channelConfig) {
    const { value } = enrichedMessage;
    const { warnThreshold, critThreshold } = channelConfig;

    const isCritical = value >= critThreshold;
    const isWarning  = !isCritical && value >= warnThreshold;

    return {
      isWarning,
      isCritical,
      reason: isCritical
        ? `value ${value} >= critical threshold ${critThreshold}`
        : isWarning
        ? `value ${value} >= warning threshold ${warnThreshold}`
        : `value ${value} within bounds`,
    };
  }
}
