// Generated by Claude Code — CS 3660 Sprint 2
import 'dotenv/config';

export const config = {
  mqtt: {
    url: process.env.MQTT_URL ?? 'mqtt://mqtt.uvucs.org:1883',
    username: process.env.MQTT_USER ?? '',
    password: process.env.MQTT_PASS ?? '',
  },
  ollama: {
    url: process.env.OLLAMA_URL ?? 'http://localhost:11434',
    model: process.env.OLLAMA_MODEL ?? 'gpt-oss:120b',
  },
  authToken: process.env.AUTH_TOKEN ?? 'changeme',
  sqlitePath: process.env.SQLITE_PATH ?? './data/events.db',
  alertEngine: {
    sustainedReadings: parseInt(process.env.SUSTAINED_READINGS ?? '3', 10),
    hysteresisMargin: parseFloat(process.env.HYSTERESIS_MARGIN ?? '5'),
    stalenessMs: parseInt(process.env.STALENESS_MS ?? '30000', 10),
  },
};
