// Generated by Claude Code — CS 3660 Sprint 2
// Pattern: Publish-Subscribe Channel (EIP)
// https://www.enterpriseintegrationpatterns.com/patterns/messaging/PublishSubscribeChannel.html
//
// Factory that creates a connected MQTT client. Every component in this system
// subscribes to the shared broker independently, making each one a separate
// subscriber on the publish-subscribe channel. The broker fans out each message
// to all subscribers without any coupling between them.

import mqtt from 'mqtt';
import { config } from '../config.js';

/**
 * Create and return a connected MQTT client.
 *
 * @param {string} clientId - Stable, unique client ID for this component.
 * @param {object} [opts]   - Optional overrides merged into the connect options.
 * @returns {Promise<import('mqtt').MqttClient>}
 */
export async function createBusClient(clientId, opts = {}) {
  const client = mqtt.connect(config.mqtt.url, {
    clientId,
    username: config.mqtt.username,
    password: config.mqtt.password,
    clean: false,          // resume session on reconnect (Rating 1 robustness)
    reconnectPeriod: 2000, // retry every 2s on disconnect
    ...opts,
  });

  await new Promise((resolve, reject) => {
    client.once('connect', resolve);
    client.once('error', reject);
  });

  client.on('error', (err) => {
    console.error(`[mqttBus] ${clientId} error:`, err.message);
  });

  console.log(`[mqttBus] ${clientId} connected to ${config.mqtt.url}`);
  return client;
}
